kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-alumet_cluster_role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/logs
      - pods/status
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-alumet-reader

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-alumet_cluster_role_binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-alumet_cluster_role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-alumet-reader
    namespace: {{ .Release.Namespace }}
