alumet-relay-server:
  enabled: true
  plugins:
    influxdb:
      enable: true
      organization: 'influxdata'
      bucket: 'default'
      attributes_as: 'tag'
      existingSecret: ''

alumet-relay-client:
  enabled: true

influxdb2:
  enabled: true
  attributes_as: 'tag'
  adminUser:
    bucket: default
    organization: 'influxdata'
  existingSecret: ''

global:
  image:
    registry: ghcr.io/alumet-dev
  # Use an existing secret as imagePullSecret in the sub charts.
  # secret: registry-secret
