imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

securityContext:
  capabilities:
    add:
      - SYS_ADMIN
      - SYS_NICE
      - PERFMON

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  # You can also add some requests if you want, here is an example.
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []

image:
  # Override appVersion and use different image version of ALUMET.
  # version: 0.8.3-1
  # Operating System deployed (debian_12, ubuntu_24.04, fc42, ubi9.5, ubi8.3)
  revision: 2
  osVersion: ubuntu_24.04
  registry:

# set environment variables for log and trace level
env:
  RUST_LOG: 'info'
  RUST_BACKTRACE: ''

# by default the config map is created at deployment step,
# but you can create your own config map to have a complete custom configuration, in that case you need to declare the config map name
configMap:
  name: ''

# set enable variable to true/false to activate/deactivate Alumet plugins
plugins:
  csv:
    enable: false
  aggregation:
    enable: false
    metrics: 'cpu_time_delta'
  energyAttribution:
    enable: false
    metrics: 'cpu_time_delta'
    filter:
      kind: 'total'
  EnergyEstimationTdp:
    enable: false
    poll_interval: 1s
    tdp: 100
    nb_vcpu: 1
    nb_cpu: 1
    cpu_usage_per_pod: 'cpu_time_delta'
  jetson:
    enable: false
  k8s:
    enable: true
    kubepods_path: '/sys/fs/cgroup/kubepods.slice/'
    poll_interval: 1s
  nvml:
    enable: false
  oar:
    enable: false
    version: oar3
    jobs_only: true
  perf:
    enable: false
  procfs:
    enable: false
  rapl:
    enable: false
    poll_interval: 1s
    flush_interval: 5s
  relay_client:
    enable: true
    port: 50051
    relay_server:
    buffer_max_length: 200
    buffer_timeout: 30s
  socket_control:
    enable: false
  opentelemetry:
    enable: false
    collector_host: 'http://localhost:4317'
    push_interval_seconds: 5
  prometheusExporter:
    enable: false
    port: 9091
