name: Chart validation

on:
  pull_request:
    branches:
      - main

jobs:
  helm-unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: azure/setup-helm@v4
        with:
          version: 3.19.0

      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run tests
        working-directory: charts/alumet
        run: helm unittest .

  helm-chart-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: azure/setup-helm@v4
        with:
          version: 3.19.0

      - uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --charts charts/alumet --charts charts/alumet/charts/alumet-relay-client --charts charts/alumet/charts/alumet-relay-server

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          config: .github/.kind-config.yaml

      - name: Run chart-testing (install)
        run: |
          helm repo add influxdata https://helm.influxdata.com/
          ct install --config ct.yaml --charts charts/alumet
